title: Anil Bhatta, PhD # your name (or website title) here
logo: "/images/screen-shot-2018-11-27-at-5-21-41-pm-160x160@2x.webp?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Data Science Fellow at Øptimus Consulting and work with both the Data Science and Data Operations team. My work is primarily done in Python and SQL. My primary effort focuses on machine learning, predictive modeling, experimental design, technical writing, and client engagement.  
  <br><br>
  My academic background is in Biomedical Sciences. I earned a PhD in Pharmacology from the Medical College of Georgia in 2015 and completed a Postdoctoral Fellowship at Johns Hopkins University School of Medicine, focusing in Tissue Engineering and Vascular Biology. I have published over 20 peer reviewed publications and conference proceedings and have received over 200 citations. 
  <br><br>
  <a href="https://www.https://www.linkedin.com/in/anilbhatta5/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
